### ISSUE TITLE
"Inline" links return 404

### ISSUE THREAD

**Issue by limitedeternity** [dutchcoders/transfer.sh#151]
GET request to [inline link](https://transfer.sh/inline/4kqT8/hello.txt) results in 404 response.

**Comment by aspacca** [comment]
transfer.sh is the hosting part of the project, it's managed by @nl5887 and I don't have his news since a month or more. I'm quite sure I didn't update yet the instance to the latest changes.

I'm sorry @limitedeternity if you contributed to the project hoping to have the features deployed on transfer.sh

**Comment by limitedeternity** [comment]
> I'm quite sure he haven't update yet the instance to the latest changes.

Yep, I thought so. 

> I'm sorry @limitedeternity if you contributed to the project hoping to have the features deployed on transfer.sh

No need to excuse. I contributed to this project just because I wanted to. 

Anyway, I think this issue should be open till the image with changes is deployed. If you don't mind, ofc.

**Comment by aspacca** [comment]
@limitedeternity the site is going to be closed at the end of the month, since this issue was related to the site I'm closing it
