### ISSUE TITLE
Could not save meta data with curl or when using the web gui

### ISSUE THREAD

**Issue by vsag96** [dutchcoders/transfer.sh#190]
Hi,

When using curl --upload-file,

What's happening:
Could not save metadata
What Should Happend:
transfer.sh/<unique-hash>/file_name_given_with_curl

It was working fine this morning, I have noticed this right now.

**Comment by marcelstoer** [comment]
This is unrelated to this software repository. transfer.sh is now run by storj.io. Please send an email to support@storj.io.

In the last 10 days it has been very unreliable for me. I'm uploading close to 400 files every day (distributed over 24h) and I'm seeing frequent hiccups. Very annoying, indeed.

I suggest you close this issue here.

**Comment by Octolus** [comment]
Same issue now

**Comment by aspacca** [comment]
@Octolus the service hosted on https://transfer.sh is not related to this repo, sorry

**Comment by ramonmedeiros** [comment]
There is a similar service called file.io:


https://stackoverflow.com/questions/59748185/cannot-upload-file-to-transfer-sh-error-could-no-save-metadata/59748186#59748186

**Comment by szafranski** [comment]
Any updates? Service was working absolutely fine for me for few days and now it says 
"could not save metadata" :(
