### ISSUE TITLE
transfer.sh is down

### ISSUE THREAD

**Issue by tcuje** [dutchcoders/transfer.sh#198]
again. At least from Germany.

https://downforeveryoneorjustme.com/transfer.sh works

**Comment by tcuje** [comment]
ping transfer.sh returns
`64 bytes from srv01.production.stefan-benten.de (144.76.136.153): icmp_seq=1 ttl=54 time=15.6 ms`
which seems ok

also appears offline for github.com, can't upload any files from travis.ci

**Comment by vitorgalvao** [comment]
Seems like it’s taking longer than usual to fix. Since Storj Labs stepped in, transfer.sh is (way) less reliable, and I don’t understand why. From [their website](https://storj.io/), this seems like the kind of stuff they should excel at, which means they are hurting their brand by not keeping transfer.sh in shape.

Is there any document that explains why the service has become worse? What are their struggles? I’d like to know if there’s something we can do to bring the service’s usability back up.

**Comment by vitorgalvao** [comment]
I asked them on Twitter and [got a reply](https://twitter.com/stefan_benten/status/1105196764313862144):

> Hey! As we are in the process of migrating to V3, there sadly a few bumps along the way. In the second of this post, we are pushing hard to spin up the Alpha Version which works against the new V3 Network. Stay tuned for that and apologizes for the trouble lately.

**Comment by ilyamordasov** [comment]
still transfer.sh is down ;(

**Comment by ocavue** [comment]
we can choice firefox send instead of transfer.sh

Website: https://send.firefox.com
Unofficial CLI tool: https://github.com/ehuggett/send-cli

**Comment by vitorgalvao** [comment]
> still transfer.sh is down ;(

Not still, but again. It was working great a few days ago.

> we can choice firefox send instead of transfer.sh

Doesn’t compare. There are tons of services that can upload files from the command line, I’ve even [made a script that supports several of them](https://github.com/vitorgalvao/tiny-scripts/blob/69d3fc35ddee7e29bf238eb50f5c226622de228b/upload-file#L4). What makes transfer.sh standout is that you can *download* the files from the command line as well with a constant URL. I’m not aware of any other service that does that.

I genuinely don’t get why people are enthusiastic about Firefox Send. I see nothing that it does better than other services, but I do see things it does worse. And being backed by Mozilla, I’m just waiting for them to abandon it like they do everything else. They keep wasting time with projects that lead nowhere (even good ones where they should have bet more, like Persona) instead of improving Firefox, which quite frankly is lacklustre on macOS.

**Comment by ilyamordasov** [comment]
@ocavue send.firefox works with websocket as I can see, I'd prefer to use something like curl
@vitorgalvao alternative services are good (seems they looked the same) will try to use one of them until transfer.sh is up (that's a pity I can't extract the full direct path to the uploaded file to use with wget)

**Comment by vitorgalvao** [comment]
> seems they looked the same

Their API is the same, but since they’re hosted in different places, if one is down it’s just a matter of switching to one of the others.

> that's a pity I can't extract the full direct path to the uploaded file

Yep. That feature alone keeps me tied to transfer.sh.

**Comment by aspacca** [comment]
or you can just host the service on your onw

**Comment by marianposaceanu** [comment]
You can also use https://temp.sh via curl (it seems everything in this thread is not working anymore) - I'm leaving the comment since this tops out in search engines and might save someone some time ☝️

```
curl -F "file=@your_file.tar.gz" https://temp.sh/upload
```

CLI alternatives (they require installation):
- https://github.com/magic-wormhole/magic-wormhole
- https://github.com/schollz/croc

**Comment by aspacca** [comment]
@stefanbenten happens to be a maintainer of this repository _and_ the person who hosts https://transfer.sh.

The two are anyway unrelated, and the repo is not the place to direct requests and issues for the website.

I will updated soon the README in order to make it clear. No third-party public installation of the software in the repo will be referred in the repo itself, for security reasons.

The official position of me, @aspacca, as maintainer of the repo, is that if you want to use the software you should host your own installation.
