### ISSUE TITLE
down ?

### ISSUE THREAD

**Issue by theaayushanand** [dutchcoders/transfer.sh#210]

**Comment by ChadTaljaardt** [comment]
Nope, back up.

**Comment by theaayushanand** [comment]
its been down a lot lately . are you guys suffering with bad traffic ?

**Comment by zervankoru** [comment]
I cant open web site

**Comment by JustAnotherArchivist** [comment]
The service at https://transfer.sh/ is no longer operated by the maintainers of this repository. Your best bet might be contacting [Storj via Twitter](https://twitter.com/storjproject); they seem to be quite responsive there.

@aspacca Since people keep asking here, it might be a good idea to add a big fat notice somewhere (e.g. README and issue template), remove the link from the repository description, and talk to Storj to get the homepage adjusted so that it's clearer who's running it.

**Comment by linuxct** [comment]
Agreed with @JustAnotherArchivist, I also came here and opened a new issue without checking previous ones such as this one. Indeed they are having lots of troubles, and I like the idea of a big notice or even a project rename to avoid getting the transfer.sh service and transfer.sh open source project linked. 

Thanks a lot.
