### ISSUE TITLE
Option to disable the frontend

### ISSUE THREAD

**Issue by AlexGustafsson** [dutchcoders/transfer.sh#222]
I'd like to run the service as a pure CLI-experience. For self-hosted purposes I have no reason to have the frontend enabled. An option to disable the frontend would be nice.

**Comment by mckaygerhard** [comment]
umm, the frontend are not also a pure-cli solution.. that can be selfthosted?

**Comment by aspacca** [comment]
@AlexGustafsson I don't understand what you refer to with frontend, can you explain more in details?

**Comment by AlexGustafsson** [comment]
Running the docker file, the service hosted a website (frontend). I’m interested in disabling said frontend and only allow the routes necessary for CLI based upload.

I’m after an option to disable the website part of the service, basically.

**Comment by aspacca** [comment]
the whole service is on http, it doesn't host a website: two of the routes render html pages (the home and the preview), if you never call those url the html pages will be never be rendered.

also, consider that the docker image from official repo is not updated since few months and I cannot fix it.

**Comment by AlexGustafsson** [comment]
I am aware the service is on HTTP. I’d like an option to disable the routes for rendering the website itself.

Thanks for the heads up on the state of the docker image.

**Comment by aspacca** [comment]
sorry @AlexGustafsson , i really don't see any value in disabling the routes when not calling them produces exactly the same results

**Comment by AlexGustafsson** [comment]
@aspacca Hosting the service lets people visit the site. There are some options to protect the service using basic auto, but that is not honoured by the website.

By disabling the website, one can push files and share them using the links. No one can however use or see the service, except for the shared files if given an URL.

**Comment by aspacca** [comment]
@AlexGustafsson pushing files and sharing the links is actually using the service, and this is not related to having the home and preview routes exposed or not.
you can put a basic auth on upload routes so that even if I load the home I cannot upload
and if you share the links and you are ok from downloading from cli if given an url why do you really care about the fact that the people you give the url can open the page in the browser instead of using the cli?
I don't see any real problem that this will actually solve that you cannot already solve with the features already provided
