### ISSUE TITLE
What happened to transfer.sh??

### ISSUE THREAD

**Issue by ilium007** [dutchcoders/transfer.sh#326]
<img width="934" alt="image" src="https://user-images.githubusercontent.com/732766/92374550-3a36e380-f143-11ea-95ed-7c5c91bb953e.png">

**Comment by aspacca** [comment]
@ilium007 not sure what is going on. Storj Labs doesn't seem interested in the project as far as I can see from their stale PRs. the domain was renewed on May and will not expire until the same month next year (you can check from whois).
I don't know what they mean about not owning the service: the code is open source and if they want they could just host on a different domain.

**Comment by rubenmdh** [comment]
It is really unfortunate to see how the transfer.sh project has gone this way.
I discovered it a while back before they announced Storj Labs would take the lead of the main instance. Ever since, it has been inconsistent and unreliable for me. That's why I just opted to host my own instance and I even registered the tranfer.re domain for the purpose, now expired.

I am still hosting a rather "private" instance but I am willing to share my server resources if that means that transfer.sh will keep operating.

It seems that the final date has been extended for a month:

> As of October 30th 2020, Storj Labs will discontinue support for the transfer.sh service. Please sign up for the world's best decentralized file transfer and storage system,tardigrade.io for all of your file transfer needs. 1. Create a tardigrade.io account. 2. Download the Uplink Tool. 3. Share your file.
> If you have any questions, please contact hello@dutchcoders.io.

**Comment by aspacca** [comment]
@rubenmdh it is not my insterest to support public hosting of the project but in the past I thought about asking sponsorship in terms of free storage to either AWS or Google (the two cloud storage that transfer.sh supports): you could try the same maybe

as for the Storj decision: they opened a PR https://github.com/dutchcoders/transfer.sh/pull/266 for adding native support to their storage one year ago. they clearly lost interest in finalising it since I approved the request on March asking them to force a CI run and they haven't answered since then.

The only problem I can see why they have to discontinue transfer.sh due to not be able to contact @nl5887 is that they need to change the ip of the domain and they don't have access to the DNS management.

no one at Storj contacted me to ask if I'm still in contact with Remco and I can arrange for them

**Comment by SimplyCorey** [comment]
For anyone interested in using a hosted service, I have built https://keep.sh as a free alternative for when transfer.sh goes offline.  

If this comment isn't welcome here, please feel free to delete.

**Comment by mckaygerhard** [comment]
hi @SimplyCorey  where is the code of the keep.sh to property compared and learn.. maybe i can provide hosting but my owners want to learn and analize if are easy .. they can sponsored cos are interesting in it

**Comment by aspacca** [comment]
@mckaygerhard what about using **this** project (transfer.sh) to provide hosting? :)

**Comment by hyOzd** [comment]
What about `https://transfersh.com/`? Is this legitimate?

**Comment by gvasilakiss** [comment]
@hyOzd That's what I got back 

Detected malware: Cloud Malware
Access from your browser has been blocked.

**Comment by Megver83** [comment]
isn't https://transfersh.com almost the same as what transfer.sh used to be? at least for me it works like transfer.sh, haven't found problems yet

**Comment by stefanbenten** [comment]
Hello everyone,

i can share some light on the issue and turn down of transfer.sh. The owner of the domain and DNS, did not respond to our requests for more than half a year. We had to do some changes to our service, which involved changes to the DNS and the respective servers hosting it. As two deadlines have gone by, we saw no other option than sadly shutting it down.

The PRs have been stale mostly due to refused changes to the structure of the codebase. Since then we have not been able to circumvent those.

**Comment by aspacca** [comment]
glad to finally have a feedback @stefanbenten 

regarding the PRs:
https://github.com/dutchcoders/transfer.sh/pull/266 I approved this on 24th March and asked you to rerun CI, no answer since then. The PR is already approved: as I wrote back then "after a green run I can merge"

https://github.com/dutchcoders/transfer.sh/pull/294: we discussed by mail the architecture of the changes and what I would have approved and what not. you decided to open the PR with changes you know I would have not approved anyway. Also even if I'd approve the changes there's no GDrive support of your solution in that PR so it would be hard to merge it since it's incomplete

> Since then we have not been able to circumvent those.

what do you actually have to circonvent? other that implementing the code fulfulling the architecture we discussed by mail?

Just to clarify for the public: I was never asked about trying to contact the original maintainer (and presumably the owner of the domain and DNS) in order to solve the issue with the site, neither I was involved in anything else. I could have try to help in case
