### ISSUE TITLE
Transfer.sh Deletion via browser returns 405 error, reconsider implementation for Delete via Get request?

### ISSUE THREAD

**Issue by beriner** [dutchcoders/transfer.sh#353]
Hi @stefanbenten ! I read through implementation discussion here: https://github.com/dutchcoders/transfer.sh/issues/44#issuecomment-399234697. 
So I understand it is not an issue with the code. It is the the website transfer.sh that should provide a delete form to process the delete GET-request, correct? So my wish would be that such a page would be set up for transfer.sh so that deletes can be successfully performed..

I'd also appreciate a reconsideration of that discussion. In my view a direct delete by a GET request (without DELETE header) should be made possible without the need for an additional form or button. To prevent accidental or malicious deletes via crawler the delete link should be constructed more randomly with longer passwords and should be different from the download links and not derived from them. I believe atm they are too similar and can be easily computed if the download link is known.

_Originally posted by @beriner in https://github.com/dutchcoders/transfer.sh/issues/351#issuecomment-783746108_

**Comment by beriner** [comment]
If a Get-Request for deletion would be some really long and random string, wouldn't that be sufficient against malicious deletions or deletions by crawlers?
As we see with transfer.sh website, deletion by browser is not set up (maybe intentional, maybe in error), so atm files cannot be deleted via browser on that site.
This shows that it would be certainly much simpler and easier for the user as well as the website operator if deletion via browser would not require additional setup or additional form/button action but could be done via GET-request.

**Comment by stefanbenten** [comment]
@aspacca I would like to get your opinion and insight on this 👍

**Comment by aspacca** [comment]
@stefanbenten I usually focus more with cli interaction and that's the reason why I didn't implement a delete mechanism on the UI. for me transfer.sh is still a cli focused service, I would have some concerns in providing the delete functionality in UI especially if it expected to work without requiring `additional setup or additional form/button action but could be done via GET-request`

One solution could be to print the `X-Delete-Url` on the upload form as well, and to provide a specific url on the UI that will ask the user for the url to submit (as provided secret) that will peform a `DELETE` request by ajax.

I don't see the value for a solution without form/button: other than being prone to abuse, the only reason for it would be to allow unattended/scripted deletion, but for that we have already the `DELETE` method

**Comment by stefanbenten** [comment]
I totally got that impression and tend to agree with that.
Still want to give more people a chance to provide options and solutions.

**Comment by beriner** [comment]
I think the transfer.sh website should provide a way to perform deletions through the browser. With form/button or without either way is fine. But there should be a way for deletion right from that website. That's number one.

Number two is the code. And for
> I don't see the value for a solution without form/button: other than being prone to abuse, the only reason for it would be to allow unattended/scripted deletion, but for that we have already the `DELETE` method

I don't see an argument against GET-request here. The functionality for scripted deletion is already there and unattended/scripted deletion can be already performed. So I cannot see why one method is considered less abusive than another one. If somebody wants to script/abuse a mass deletion, it is already possible with a variety of tools (Curl, Powetshell etc.).

And number three is:
Current share link looks like this: https://transfer.sh/eibhM/hello.txt
Current deletion link looks like this: https://transfer.sh/eibhM/hello.txt/SECRETCODE
While SECRECTCODE appears to be either 10 characters or 11 characters (haven't seen less or more) in all cases.

**This** is prone to abuse as once the share link is known, the deletion link can be computed with low effort.

Therefore the deletion link should not share any parts with the share link and should be created as a much longer random string only, something like https://transfer.sh/02e620eadbde7fc2ab55939ab1e4d402f077a2829bfe2d1c4709b6c1a630b1febf012c87a2a639f87b0c2d201db10cd891bf5572651c26991e3d4c9324eec727
The string could be generated as a long random password, or as the result of some secure hashing function with multiple random re-hashes. 

If such was implemented, I don't see how deletion by Get-request would be more prone to scripted deletions and potential abuse than the implementation today.

**Comment by JustAnotherArchivist** [comment]
I'd like to bring up a point that hasn't been mentioned yet at all: HTTP semantics. `GET` is not meant to alter server state. Its meaning is to 'transfer a current representation of the target resource', as RFC 7231 puts it. The `DELETE` method specifically exists to delete a resource.

Deleting a file with a `GET` request – or really anything but `DELETE` – would be an abuse of the HTTP spec, in my opinion.

As for how to implement deletion through the web interface: sadly, it isn't possible to do `DELETE` requests without JavaScript. However, the web interface doesn't support uploads without JS anyway (as far as I know), so that's probably not a hindrance. `XMLHttpRequest` supports `DELETE` requests.

**Comment by aspacca** [comment]
@JustAnotherArchivist completely agree, and that was (one of) the ratio behind my proposed implentation

>One solution could be to print the X-Delete-Url on the upload form as well, and to provide a specific url on the UI that will ask the user for the url to submit (as provided secret) that will peform a DELETE request by ajax.

**Comment by JustAnotherArchivist** [comment]
Yeah, an endpoint with a small form would work. Or a `GET` request on the deletion URL could return a UI that, possibly after asking the user for confirmation, triggers a `DELETE` request via `XMLHttpRequest` for the actual deletion.

**Comment by aspacca** [comment]
@beriner 

> This is prone to abuse as once the share link is known, the deletion link can be computed with low effort.

https://github.com/dutchcoders/transfer.sh/pull/372 now address the brute force issue

while 5/6 alphanum mixed-case chars for the upload url are easily brute forcebale, 10/11 would be safe enough

https://tmedweb.tulane.edu/content_open/bfcalc.php
https://www.betterbuys.com/estimating-password-cracking-times/

we could go even further and decouple the deletion url from the upload url

the main thing is that transer.sh, as far as I see it, is mainly as a shell "bound" service

I understand there could be a lot of users that just use the UI and use it as web service, and meeting their needs should be taken in account: it's just a matter to find the right solution without compromising the nature of the project and other consideration like the one from @JustAnotherArchivist

**Comment by aspacca** [comment]
I've a local branch on transfer.sh-web with UI change for allowing deletion:
1. On upload page we print as well the `X-Url-Delete` header
<img width="667" alt="deletion-UI-01" src="https://user-images.githubusercontent.com/221530/120065043-a52c9f80-c06f-11eb-879a-985c4471e7e3.png">

2. Added a `Delete` button on the preview page:
<img width="682" alt="deletion-UI-02" src="https://user-images.githubusercontent.com/221530/120065042-a52c9f80-c06f-11eb-90d5-774aaada8997.png">

3. Clicking on the `Delete` button toggles the deletion dialog
<img width="675" alt="deletion-UI-03" src="https://user-images.githubusercontent.com/221530/120065041-a4940900-c06f-11eb-97f3-11ebb30dab82.png">

4. Sending the wrong deletion token prints an error in the dialog, without removing input and confirm button. The same happen for every other error.
<img width="668" alt="deletion-UI-04" src="https://user-images.githubusercontent.com/221530/120065040-a3fb7280-c06f-11eb-9217-be189cc6a8c1.png">

5. If the deletion token is correct and the `DELETE` action succeded a message is shown removing input and confirm button.
<img width="666" alt="deletion-UI-05" src="https://user-images.githubusercontent.com/221530/120065039-a2ca4580-c06f-11eb-9dfd-01bd4fa1e34d.png">

No changes in the backend: it's just UI sugar that does a `DELETE` request to the backend building the url from known token and provided deletion token.

@beriner , @JustAnotherArchivist , @stefanbenten what do you think?

**Comment by JustAnotherArchivist** [comment]
People who aren't familiar with the internal terminology will likely struggle to understand what the 'deletion token' is since I don't think that term is used anywhere else in the UI. I see two possible approaches to fix that: introduce the term on the upload, i.e. show the deletion token after upload, not the deletion URL; or avoid the term and use the full deletion URL instead.
I'd prefer the latter. The deletion URL already exists and obviously won't go away, although the casual user won't ever have seen it before. If the token were exposed now, this would *appear* like a different method of deleting files, and people might not realise that they are really identical and can be transformed into each other.

I feel like the cleanest UI would be to display a similar page to your proposed on `GET` against the deletion URL. The button would then directly trigger the `DELETE` request against the `location.href` rather than prompting for a token, of course.

On a related note, there should probably be an example how to delete a file with curl in the expanded use cases on the homepage. I guess it doesn't make sense to add this to the post-upload message to avoid clutter. But I feel like such an example combined with the approach above would make for a fairly clear interface and communicate well to the user that this is interchangeable. Adding the deletion URL to the shell function might make sense as well, but no idea how to do that cleanly (my own hacky script uses `curl -v` and then runs `grep` on the stderr to get the deletion URL...).

**Comment by aspacca** [comment]
> People who aren't familiar with the internal terminology will likely struggle to understand what the 'deletion token' is

fair point

@stefanbenten what do you think is best? asking for the full `DELETE` url or printing just the deletion token on upload?

> I feel like the cleanest UI would be to display a similar page to your proposed on GET against the deletion URL. The button would then directly trigger the DELETE request against the location.href rather than prompting for a token, of course.

that's what I'm refrained to do: the deletion token (or the full delete url) should be threated as a confirmation secret to trigger the deletion. while providing a confirm button would make the thing just a little harder for abuse, it won't be enough in my opinion.

as for the the curl examples, feel free to open a PR with such, or just an issue with it and I will incorporate in a PR

**Comment by stefanbenten** [comment]
In my mind the deletion page would require some sort of captcha. I am not opposed to either route, possibly printing just the token for scripted deletion without captcha on upload and having the actual full URL with the confirmation button + captcha on the WebUI solves this?

**Comment by aspacca** [comment]
What do you mean exactly for captcha @stefanbenten?

I would be fine having a bot performing the deletion, as long as it would need a secret to perform it (complex enough to not be brute forced)

Also I wouldn't support any solution that would require to enable cookies or relying on third party services: I'm not aware of any captcha solution fulfilling this requirements but if they exists I would consider

**Comment by aspacca** [comment]
In general I would go for the proposed solution (see the screenshots https://github.com/dutchcoders/transfer.sh/issues/353#issuecomment-850802916)

I would rather print only the deletion token instead of the deletion url in the upload page, since it seems cleaner to me.
But I understand the concern from @JustAnotherArchivist that we would hide information about the fact the is the whole deletion url required for the action. Honestly I think the UI-only user doesn't need this information, while the CLI user, occasionally using the UI, will be able to understand the nuance.

I have to test with multiple uploads from UI

**Comment by stefanbenten** [comment]
Thats true, all captcha services i would use, would be third party.

Technically the deletion field could simply parse if the string starts with a schema like https:// and then strip it. Then both the full URL as well as we actual token would work.
I think the solution proposed is totally clear then.
