### ISSUE TITLE
Error while using Storj as provider 

### ISSUE THREAD

**Issue by driftywinds** [dutchcoders/transfer.sh#448]
The server starts up normally while using docker, but when I try to upload any file from UI or command line the server shows me this error in the console: - 
```
 Error putting new file: uplink: stream: open /tmp/tee633693309: no such file or directory
```
Also the --basedir flag does not change the directory for some reason and it always uses /tmp/

**Comment by stefanbenten** [comment]
@driftywinds basedir is not used at all for the storage provider, only when using local storage.
Could you paste your entire docker run command here, redacting secrets of course.

**Comment by driftywinds** [comment]
> @driftywinds basedir is not used at all for the storj storage provider, only when using local storage. Could you paste your entire docker run command here, redacting secrets of course.

@stefanbenten my command is: -
```
docker run --publish 4444:8080 dutchcoders/transfer.sh:latest --provider storj --storj-access <access key> --storj-bucket <bucket> --max-upload-size 2097152 --purge-days 30 --purge-interval 12 --rate-limit 5
```
I then use caddy to reverse proxy the server running at port 4444 to my domain

**Comment by driftywinds** [comment]
Any leads?

**Comment by stefanbenten** [comment]
@driftywinds I did not had time to look into this.
Will get to it today 🙏

**Comment by stefanbenten** [comment]
@driftywinds After going down the rabbit hole i have found out its actually a dependency that the Storj provider uses itself and thus is not easy able to change.
There are now two ways to solve this:

a) use a smaller image like apline or debian small instead of the scratch image as base see [Dockerfile](https://github.com/dutchcoders/transfer.sh/blob/acd6fb084f2804a5eea5b79bf8f82612e74a4b43/Dockerfile#L17)
b) add `--mount type=tmpfs,destination=/tmp/` to your run command above (comes at the drawback of using your max file size times the concurrent upload count you may observe).

In terms of making this more robust, i would suggest for the short term to use option b) and @aspacca and I need to chat about switching the image for option a)

**Comment by aspacca** [comment]
@stefanbenten what's the dependency?

I would like to understand if we have a workaround before using alpine as base image

**Comment by stefanbenten** [comment]
@aspacca I am looking into this now and possibly found a workaround.
