### ISSUE TITLE
Guide for deploying on Synology?

### ISSUE THREAD

**Issue by kzssc** [dutchcoders/transfer.sh#489]
Sorry for the noob question - but I wonder devs might lend me a hand on deploying transfer.sh onto my synology NAS via docker, please? Many thanks! :))

**Comment by aspacca** [comment]
hello @kzssc , it depends on the synology model, according the its cpu

what model do you have?

is it fine for you to deploy from shell or do you want to deploy from the docker manager on the DSM?

**Comment by kzssc** [comment]
Hiiiii thanks for the reply! I'm currently on 218+. I don't mind whichever way but I think Docker might be easier? haha!

**Comment by aspacca** [comment]
it's indeed esier to user directly the compiled binary available from the releases, since we build for a lot of OSes and platform

for the ds 218+ this one should be the right one https://github.com/dutchcoders/transfer.sh/releases/download/v1.4.0/transfersh-v1.4.0-linux-arm64-v8a

arm64 v8

just donwload that somewhere in your path on the syno and starts it from the shell
you can  probably have a scheduled task in the dsm to let it start at boot: https://kb.synology.com/en-global/DSM/help/DSM/AdminCenter/system_taskscheduler?version=7
