### ISSUE TITLE
can you support IPFS storage and chrome PWA?

### ISSUE THREAD

**Issue by phpmac** [dutchcoders/transfer.sh#499]
can you support IPFS storage and chrome PWA?

[IPFS](https://ipfs.io/) is blockchain.

PWA is Chrome App

**Comment by stefanbenten** [comment]
Hello @phpmac,

we certainly could add an IPFS connector to transfer.sh. However, due to the short lifetime of the content (transfer.sh is 14 days), the use case is somewhat less useful in my eyes. Further, transfer.sh tracks downloads, which would be not possible when content is cached on other IPFS nodes.
Could you explain the usecase on your end @phpmac ?

**Comment by aspacca** [comment]
closing as stale
