### ISSUE TITLE
romanian ips are blocked from accessing transfer.sh

### ISSUE THREAD

**Issue by nnvape** [dutchcoders/transfer.sh#596]
whenever i try to go on transfer.sh or upload a file i get errors that it cant connect but when i use a poland proxy i can access the website and upload files

**Comment by nnvape** [comment]
possibly russian ips too

**Comment by stefanbenten** [comment]
Abusing countries have been excluded from the service. Without requiring more user information for usage, we will have to keep countries excluded.

**Comment by Bellavene** [comment]
What does "abusing countries" mean?

**Comment by sergeevabc** [comment]
> @Bellavene
> What does "abusing countries" mean?

It is a “[No Jews allowed][1]” sign in the 21 century.
Look at the bio of @stefanbenten, he's coming from Germany.
Ask yourself, what his grandpa did for a living. The apple doesn't fall far from the tree.

[1]: https://www.annefrank.org/en/timeline/219/forbidden-for-jews/

**Comment by aspacca** [comment]
@sergeevabc , i apologize, your comment is against the code of conduct of this repository.
it's also in the wrong place, since as clearly explained in the readme this repo is not the place where to address any concern for the service that @stefanbenten hosts.
please next time do your best to address your frustration about him and the service he hosts directly to him, without using the public space that's available here with no regard for the code of conduct.

you're welcome for anything else
